#!/usr/bin/env python3
"""build_midi_spy.py - capture the MIDI itself, one layer lower.

The first capture rig stood in for `5868USB.dll` and saw nothing: Suite loads
that library and then, for everything except firmware updates and NAM
conversion, does not call it. The MIDI goes straight from Dart to **winmm** -
`flutter_midi_command_windows` is FFI, not a plugin DLL, and there is no plugin
in the install to shim.

So this shims winmm instead, for one copy of Suite only. Windows looks in the
application's own directory before System32 for anything that is not a KnownDLL,
and winmm is not one, so a `winmm.dll` beside `Valeton Suite.exe` is what the
process gets. Everything is forwarded to a copy of the real one kept as
`winmm_real.dll`; five calls are logged:

    midiOutShortMsg     three bytes of a channel message
    midiOutLongMsg      a whole SysEx going out - this is the protocol
    midiInAddBuffer     the buffer being re-queued, which still holds the reply
                        that was just delivered - this is the device answering
    midiOutOpen         which port was opened
    midiInOpen          the same, inbound

Nothing is injected: this watches the traffic Suite generates.

    build_midi_spy.py build                      compile winmm.dll
    build_midi_spy.py install --dir <suite dir>   put it beside the exe
    build_midi_spy.py uninstall --dir <suite dir>
    build_midi_spy.py status --dir <suite dir>

Point `--dir` at a copy of Suite in a writable place - the installed one under
Program Files needs elevation and cannot be swapped while it runs.
"""

import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import build_spy                                   # noqa: E402  (exports, _cl)

SYSTEM_WINMM = os.path.join(os.environ.get('WINDIR', r'C:\Windows'),
                            'System32', 'winmm.dll')
KEPT_NAME = 'winmm_real.dll'
OUT_NAME = 'winmm.dll'

HOOKS = {
    'midiOutShortMsg': r'''
__declspec(dllexport) UINT WINAPI midiOutShortMsg(HMIDIOUT h, DWORD msg) {
    static UINT (WINAPI *fn)(HMIDIOUT, DWORD);
    if (!fn) fn = (UINT (WINAPI *)(HMIDIOUT, DWORD))sym("midiOutShortMsg");
    spy_line("out short  %02X %02X %02X", msg & 0xFF, (msg >> 8) & 0xFF,
             (msg >> 16) & 0xFF);
    return fn ? fn(h, msg) : MMSYSERR_NODRIVER;
}
''',
    'midiOutLongMsg': r'''
__declspec(dllexport) UINT WINAPI midiOutLongMsg(HMIDIOUT h, LPMIDIHDR hdr, UINT cb) {
    static UINT (WINAPI *fn)(HMIDIOUT, LPMIDIHDR, UINT);
    if (!fn) fn = (UINT (WINAPI *)(HMIDIOUT, LPMIDIHDR, UINT))sym("midiOutLongMsg");
    if (hdr && hdr->lpData) spy_hex("out sysex", (const unsigned char *)hdr->lpData,
                                    (int)hdr->dwBufferLength);
    return fn ? fn(h, hdr, cb) : MMSYSERR_NODRIVER;
}
''',
    'midiInAddBuffer': r'''
__declspec(dllexport) UINT WINAPI midiInAddBuffer(HMIDIIN h, LPMIDIHDR hdr, UINT cb) {
    static UINT (WINAPI *fn)(HMIDIIN, LPMIDIHDR, UINT);
    if (!fn) fn = (UINT (WINAPI *)(HMIDIIN, LPMIDIHDR, UINT))sym("midiInAddBuffer");
    /* A buffer is handed back after its contents have been consumed, so what is
       in it now is the reply the device just sent. */
    if (hdr && hdr->lpData && hdr->dwBytesRecorded)
        spy_hex("in  sysex", (const unsigned char *)hdr->lpData,
                (int)hdr->dwBytesRecorded);
    return fn ? fn(h, hdr, cb) : MMSYSERR_NODRIVER;
}
''',
    'midiOutOpen': r'''
__declspec(dllexport) UINT WINAPI midiOutOpen(LPHMIDIOUT ph, UINT id, DWORD_PTR cb,
                                              DWORD_PTR inst, DWORD flags) {
    static UINT (WINAPI *fn)(LPHMIDIOUT, UINT, DWORD_PTR, DWORD_PTR, DWORD);
    if (!fn) fn = (UINT (WINAPI *)(LPHMIDIOUT, UINT, DWORD_PTR, DWORD_PTR, DWORD))
                  sym("midiOutOpen");
    UINT r = fn ? fn(ph, id, cb, inst, flags) : MMSYSERR_NODRIVER;
    spy_line("midiOutOpen(device %u) -> %u", id, r);
    return r;
}
''',
    'midiInOpen': r'''
__declspec(dllexport) UINT WINAPI midiInOpen(LPHMIDIIN ph, UINT id, DWORD_PTR cb,
                                             DWORD_PTR inst, DWORD flags) {
    static UINT (WINAPI *fn)(LPHMIDIIN, UINT, DWORD_PTR, DWORD_PTR, DWORD);
    if (!fn) fn = (UINT (WINAPI *)(LPHMIDIIN, UINT, DWORD_PTR, DWORD_PTR, DWORD))
                  sym("midiInOpen");
    UINT r = fn ? fn(ph, id, cb, inst, flags) : MMSYSERR_NODRIVER;
    spy_line("midiInOpen(device %u) -> %u", id, r);
    return r;
}
''',
}

PREAMBLE = r'''/* winmm shim - generated by build_midi_spy.py. Do not edit; regenerate. */
#include <windows.h>
#include <mmsystem.h>
#include <stdio.h>
#include <share.h>

static HMODULE real;
static CRITICAL_SECTION lock;
static FILE *spy_f;

static void spy_open(void) {
    char path[MAX_PATH];
    if (spy_f) return;
    GetTempPathA(sizeof(path), path);
    strcat_s(path, sizeof(path), "gp150_midi.log");
    spy_f = _fsopen(path, "a", _SH_DENYNO);
}

static void spy_line(const char *fmt, ...) {
    va_list ap;
    EnterCriticalSection(&lock);
    spy_open();
    if (spy_f) {
        SYSTEMTIME t; GetLocalTime(&t);
        fprintf(spy_f, "%02d:%02d:%02d.%03d ", t.wHour, t.wMinute, t.wSecond,
                t.wMilliseconds);
        va_start(ap, fmt); vfprintf(spy_f, fmt, ap); va_end(ap);
        fputc('\n', spy_f); fflush(spy_f);
    }
    LeaveCriticalSection(&lock);
}

static void spy_hex(const char *what, const unsigned char *d, int n) {
    /* A firmware update is megabytes of this, so a line is capped and says so. */
    int i, m = n > 512 ? 512 : n;
    char *hex = (char *)malloc((size_t)m * 3 + 8);
    if (!hex) return;
    for (i = 0; i < m; i++) sprintf_s(hex + 3 * i, 4, "%02X ", d[i]);
    hex[3 * m] = 0;
    spy_line("%s len=%d  %s%s", what, n, hex, n > m ? "..." : "");
    free(hex);
}

static void *sym(const char *name) {
    if (!real) {
        char path[MAX_PATH]; HMODULE self = NULL;
        GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
            GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, (LPCSTR)&sym, &self);
        GetModuleFileNameA(self, path, sizeof(path));
        char *slash = strrchr(path, '\\');
        if (slash) slash[1] = 0;
        strcat_s(path, sizeof(path), "winmm_real.dll");
        real = LoadLibraryA(path);
        spy_line("== midi spy attached, real winmm %s", real ? path : "NOT FOUND");
    }
    return real ? (void *)GetProcAddress(real, name) : NULL;
}

BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID r) {
    (void)h; (void)r;
    if (reason == DLL_PROCESS_ATTACH) {
        char exe[MAX_PATH];
        InitializeCriticalSection(&lock);
        GetModuleFileNameA(NULL, exe, sizeof(exe));
        spy_line("== loaded into %s (pid %lu)", exe, GetCurrentProcessId());
    }
    return TRUE;
}
'''


def cmd_build():
    names = build_spy.exports(SYSTEM_WINMM)
    hooked = [n for n in names if n in HOOKS]
    forwarded = [n for n in names if n not in HOOKS]
    print("winmm has %d exports: %d hooked, %d forwarded"
          % (len(names), len(hooked), len(forwarded)))
    with open(os.path.join(HERE, 'midi_spy.def'), 'w', encoding='utf-8') as f:
        f.write('LIBRARY winmm\nEXPORTS\n')
        for n in hooked:
            f.write('    %s\n' % n)
        for n in forwarded:
            f.write('    %s=winmm_real.%s\n' % (n, n))
    with open(os.path.join(HERE, 'midi_spy.c'), 'w', encoding='utf-8') as f:
        f.write(PREAMBLE)
        for n in hooked:
            f.write(HOOKS[n])
    print("wrote midi_spy.c and midi_spy.def")

    cl = build_spy._cl()
    vc = cl.split(os.sep + 'bin' + os.sep)[0]
    sdk = r'C:\Program Files (x86)\Windows Kits\10'
    v = sorted(os.listdir(os.path.join(sdk, 'Include')))[-1]
    env = dict(os.environ)
    env['INCLUDE'] = ';'.join([os.path.join(vc, 'include'),
                               os.path.join(sdk, 'Include', v, 'ucrt'),
                               os.path.join(sdk, 'Include', v, 'um'),
                               os.path.join(sdk, 'Include', v, 'shared')])
    env['LIB'] = ';'.join([HERE, os.path.join(vc, 'lib', 'x64'),
                           os.path.join(sdk, 'Lib', v, 'ucrt', 'x64'),
                           os.path.join(sdk, 'Lib', v, 'um', 'x64')])
    # the forwarders need an import library for the name they point at
    with open(os.path.join(HERE, 'winmm_real.def'), 'w', encoding='utf-8') as f:
        f.write('LIBRARY winmm_real\nEXPORTS\n')
        for n in names:
            f.write('    %s\n' % n)
    libexe = os.path.join(os.path.dirname(cl), 'lib.exe')
    r = subprocess.run([libexe, '/nologo', '/def:winmm_real.def',
                        '/out:winmm_real.lib', '/machine:x64'],
                       cwd=HERE, env=env, capture_output=True, text=True)
    if r.returncode:
        print(r.stdout[-2000:], r.stderr[-2000:])
        raise SystemExit("could not make the import library")
    out = os.path.join(HERE, OUT_NAME)
    r = subprocess.run([cl, '/nologo', '/O2', '/LD', 'midi_spy.c', '/link',
                        '/DEF:midi_spy.def', 'winmm_real.lib', '/OUT:' + out],
                       cwd=HERE, env=env, capture_output=True, text=True)
    print(r.stdout[-2500:])
    if r.returncode:
        print(r.stderr[-2500:])
        raise SystemExit("build failed")
    print("built %s (%d bytes)" % (out, os.path.getsize(out)))


def paths(dirname):
    d = os.path.abspath(dirname)
    return d, os.path.join(d, OUT_NAME), os.path.join(d, KEPT_NAME)


def cmd_install(dirname):
    d, out, kept = paths(dirname)
    mine = os.path.join(HERE, OUT_NAME)
    if not os.path.isfile(mine):
        raise SystemExit("build it first")
    if not os.path.isfile(os.path.join(d, 'Valeton Suite.exe')):
        raise SystemExit("%s does not look like a Suite folder" % d)
    if not os.path.isfile(kept):
        shutil.copy2(SYSTEM_WINMM, kept)
        print("kept a copy of the system winmm as %s" % kept)
    shutil.copy2(mine, out)
    print("installed %s" % out)
    print("Start that copy of Suite; the log is %TEMP%\\gp150_midi.log")


def cmd_uninstall(dirname):
    d, out, kept = paths(dirname)
    for p in (out, kept):
        if os.path.isfile(p):
            os.remove(p)
            print("removed %s" % p)
    print("that copy of Suite is back on the system winmm")


def cmd_status(dirname):
    d, out, kept = paths(dirname)
    for p, what in ((out, 'winmm.dll (ours)'), (kept, 'winmm_real.dll (the system copy)')):
        print("  %-34s %s" % (what, "%d bytes" % os.path.getsize(p)
                              if os.path.isfile(p) else "absent"))
    log = os.path.join(os.environ.get('TEMP', ''), 'gp150_midi.log')
    print("  %-34s %s" % ("log", "%d bytes" % os.path.getsize(log)
                          if os.path.isfile(log) else "none yet"))


def main(argv):
    argv = list(argv)
    dirname = None
    if '--dir' in argv:
        i = argv.index('--dir')
        dirname = argv[i + 1]
        del argv[i:i + 2]
    if not argv:
        print(__doc__.strip())
        return 1
    if argv[0] == 'build':
        return cmd_build()
    if not dirname:
        raise SystemExit("that command needs --dir <suite folder>")
    return {'install': cmd_install, 'uninstall': cmd_uninstall,
            'status': cmd_status}.get(argv[0], lambda _d: print(__doc__.strip()))(dirname)


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]) or 0)
