/* winmm shim - generated by build_midi_spy.py. Do not edit; regenerate. */
#include <windows.h>
#include <mmsystem.h>
#include <stdio.h>
#include <share.h>

static HMODULE real;
static CRITICAL_SECTION lock;
static FILE *spy_f;

static void spy_open(void) {
    char path[MAX_PATH];
    if (spy_f) return;
    GetTempPathA(sizeof(path), path);
    strcat_s(path, sizeof(path), "gp150_midi.log");
    spy_f = _fsopen(path, "a", _SH_DENYNO);
}

static void spy_line(const char *fmt, ...) {
    va_list ap;
    EnterCriticalSection(&lock);
    spy_open();
    if (spy_f) {
        SYSTEMTIME t; GetLocalTime(&t);
        fprintf(spy_f, "%02d:%02d:%02d.%03d ", t.wHour, t.wMinute, t.wSecond,
                t.wMilliseconds);
        va_start(ap, fmt); vfprintf(spy_f, fmt, ap); va_end(ap);
        fputc('\n', spy_f); fflush(spy_f);
    }
    LeaveCriticalSection(&lock);
}

static void spy_hex(const char *what, const unsigned char *d, int n) {
    /* A firmware update is megabytes of this, so a line is capped and says so. */
    int i, m = n > 512 ? 512 : n;
    char *hex = (char *)malloc((size_t)m * 3 + 8);
    if (!hex) return;
    for (i = 0; i < m; i++) sprintf_s(hex + 3 * i, 4, "%02X ", d[i]);
    hex[3 * m] = 0;
    spy_line("%s len=%d  %s%s", what, n, hex, n > m ? "..." : "");
    free(hex);
}

static void *sym(const char *name) {
    if (!real) {
        char path[MAX_PATH]; HMODULE self = NULL;
        GetModuleHandleExA(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
            GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, (LPCSTR)&sym, &self);
        GetModuleFileNameA(self, path, sizeof(path));
        char *slash = strrchr(path, '\\');
        if (slash) slash[1] = 0;
        strcat_s(path, sizeof(path), "winmm_real.dll");
        real = LoadLibraryA(path);
        spy_line("== midi spy attached, real winmm %s", real ? path : "NOT FOUND");
    }
    return real ? (void *)GetProcAddress(real, name) : NULL;
}

BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID r) {
    (void)h; (void)r;
    if (reason == DLL_PROCESS_ATTACH) {
        char exe[MAX_PATH];
        InitializeCriticalSection(&lock);
        GetModuleFileNameA(NULL, exe, sizeof(exe));
        spy_line("== loaded into %s (pid %lu)", exe, GetCurrentProcessId());
    }
    return TRUE;
}

__declspec(dllexport) UINT WINAPI midiInAddBuffer(HMIDIIN h, LPMIDIHDR hdr, UINT cb) {
    static UINT (WINAPI *fn)(HMIDIIN, LPMIDIHDR, UINT);
    if (!fn) fn = (UINT (WINAPI *)(HMIDIIN, LPMIDIHDR, UINT))sym("midiInAddBuffer");
    /* A buffer is handed back after its contents have been consumed, so what is
       in it now is the reply the device just sent. */
    if (hdr && hdr->lpData && hdr->dwBytesRecorded)
        spy_hex("in  sysex", (const unsigned char *)hdr->lpData,
                (int)hdr->dwBytesRecorded);
    return fn ? fn(h, hdr, cb) : MMSYSERR_NODRIVER;
}

__declspec(dllexport) UINT WINAPI midiInOpen(LPHMIDIIN ph, UINT id, DWORD_PTR cb,
                                             DWORD_PTR inst, DWORD flags) {
    static UINT (WINAPI *fn)(LPHMIDIIN, UINT, DWORD_PTR, DWORD_PTR, DWORD);
    if (!fn) fn = (UINT (WINAPI *)(LPHMIDIIN, UINT, DWORD_PTR, DWORD_PTR, DWORD))
                  sym("midiInOpen");
    UINT r = fn ? fn(ph, id, cb, inst, flags) : MMSYSERR_NODRIVER;
    spy_line("midiInOpen(device %u) -> %u", id, r);
    return r;
}

__declspec(dllexport) UINT WINAPI midiOutLongMsg(HMIDIOUT h, LPMIDIHDR hdr, UINT cb) {
    static UINT (WINAPI *fn)(HMIDIOUT, LPMIDIHDR, UINT);
    if (!fn) fn = (UINT (WINAPI *)(HMIDIOUT, LPMIDIHDR, UINT))sym("midiOutLongMsg");
    if (hdr && hdr->lpData) spy_hex("out sysex", (const unsigned char *)hdr->lpData,
                                    (int)hdr->dwBufferLength);
    return fn ? fn(h, hdr, cb) : MMSYSERR_NODRIVER;
}

__declspec(dllexport) UINT WINAPI midiOutOpen(LPHMIDIOUT ph, UINT id, DWORD_PTR cb,
                                              DWORD_PTR inst, DWORD flags) {
    static UINT (WINAPI *fn)(LPHMIDIOUT, UINT, DWORD_PTR, DWORD_PTR, DWORD);
    if (!fn) fn = (UINT (WINAPI *)(LPHMIDIOUT, UINT, DWORD_PTR, DWORD_PTR, DWORD))
                  sym("midiOutOpen");
    UINT r = fn ? fn(ph, id, cb, inst, flags) : MMSYSERR_NODRIVER;
    spy_line("midiOutOpen(device %u) -> %u", id, r);
    return r;
}

__declspec(dllexport) UINT WINAPI midiOutShortMsg(HMIDIOUT h, DWORD msg) {
    static UINT (WINAPI *fn)(HMIDIOUT, DWORD);
    if (!fn) fn = (UINT (WINAPI *)(HMIDIOUT, DWORD))sym("midiOutShortMsg");
    spy_line("out short  %02X %02X %02X", msg & 0xFF, (msg >> 8) & 0xFF,
             (msg >> 16) & 0xFF);
    return fn ? fn(h, msg) : MMSYSERR_NODRIVER;
}
